config/routes.rb
Rails.application.routes.draw do
  resources :test_results
  resources :test_result_types
  resources :executions
  resources :executors

  resources :projects do 
		resources :sections do 
  		resources :test_cases, shallow: true
		end
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/test_result.rb
class TestResult < ApplicationRecord
  belongs_to :execution
  belongs_to :test_result_type
end

app/models/test_result_type.rb
class TestResultType < ApplicationRecord
end

app/controllers/test_results_controller.rb
class TestResultsController < ApplicationController
  before_action :set_test_result, only: [:show, :edit, :update, :destroy]

  # GET /test_results
  # GET /test_results.json
  def index
    @test_results = TestResult.all
  end

  # GET /test_results/1
  # GET /test_results/1.json
  def show
  end

  # GET /test_results/new
  def new
    @test_result = TestResult.new
  end

  # GET /test_results/1/edit
  def edit
  end

  # POST /test_results
  # POST /test_results.json
  def create
    @test_result = TestResult.new(test_result_params)

    respond_to do |format|
      if @test_result.save
        format.html { redirect_to @test_result, notice: 'Test result was successfully created.' }
        format.json { render :show, status: :created, location: @test_result }
      else
        format.html { render :new }
        format.json { render json: @test_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_results/1
  # PATCH/PUT /test_results/1.json
  def update
    respond_to do |format|
      if @test_result.update(test_result_params)
        format.html { redirect_to @test_result, notice: 'Test result was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_result }
      else
        format.html { render :edit }
        format.json { render json: @test_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_results/1
  # DELETE /test_results/1.json
  def destroy
    @test_result.destroy
    respond_to do |format|
      format.html { redirect_to test_results_url, notice: 'Test result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_result
      @test_result = TestResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_result_params
      params.require(:test_result).permit(:description, :finished_at, :execution_id, :test_result_type_id)
    end
end

app/helpers/test_results_helper.rb
module TestResultsHelper
end

app/views/test_results/_form.html.haml
= form_for @test_result, html: { class: "form form-horizontal test_result" } do |f|
  .form-group
    = f.label :description, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :description, class: 'form-control', required: true
    = f.error_span(:description)
  .form-group
    = f.label :finished_at, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :finished_at, class: 'form-control', required: true
    = f.error_span(:finished_at)
  .form-group
    = f.label :execution_id, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :execution_id, class: 'form-control', required: true
    = f.error_span(:execution_id)
  .form-group
    = f.label :test_result_type_id, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :test_result_type_id, class: 'form-control', required: true
    = f.error_span(:test_result_type_id)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), test_results_path, :class => 'btn btn-default'

app/views/test_results/edit.html.haml
- model_class = TestResult
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/test_results/index.html.haml
- model_class = TestResult
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:finished_at)
      %th= model_class.human_attribute_name(:execution_id)
      %th= model_class.human_attribute_name(:test_result_type_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @test_results.each do |test_result|
      %tr
        %td= link_to test_result.id, test_result_path(test_result)
        %td= test_result.description
        %td= test_result.finished_at
        %td= test_result.execution_id
        %td= test_result.test_result_type_id
        %td=l test_result.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_test_result_path(test_result), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), test_result_path(test_result), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_test_result_path, :class => 'btn btn-primary'

app/views/test_results/new.html.haml
- model_class = TestResult
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/test_results/show.html.haml
- model_class = TestResult
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @test_result.description
%p
  %strong= model_class.human_attribute_name(:finished_at) + ':'
  %br
  = @test_result.finished_at
%p
  %strong= model_class.human_attribute_name(:execution_id) + ':'
  %br
  = @test_result.execution_id
%p
  %strong= model_class.human_attribute_name(:test_result_type_id) + ':'
  %br
  = @test_result.test_result_type_id


= link_to t('.back', :default => t("helpers.links.back")), test_results_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_test_result_path(@test_result), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), test_result_path(@test_result), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'