config/routes.rb
Rails.application.routes.draw do
  resources :test_results
  resources :test_result_types
  resources :executions
  resources :executors

  resources :projects do 
		resources :sections do 
  		resources :test_cases, shallow: true
		end
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/execution.rb
class Execution < ApplicationRecord
  belongs_to :executor
end

app/controllers/executions_controller.rb
class ExecutionsController < ApplicationController
  before_action :set_execution, only: [:show, :edit, :update, :destroy]

  # GET /executions
  # GET /executions.json
  def index
    @executions = Execution.all
  end

  # GET /executions/1
  # GET /executions/1.json
  def show
  end

  # GET /executions/new
  def new
    @execution = Execution.new
  end

  # GET /executions/1/edit
  def edit
  end

  # POST /executions
  # POST /executions.json
  def create
    @execution = Execution.new(execution_params)

    respond_to do |format|
      if @execution.save
        format.html { redirect_to @execution, notice: 'Execution was successfully created.' }
        format.json { render :show, status: :created, location: @execution }
      else
        format.html { render :new }
        format.json { render json: @execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /executions/1
  # PATCH/PUT /executions/1.json
  def update
    respond_to do |format|
      if @execution.update(execution_params)
        format.html { redirect_to @execution, notice: 'Execution was successfully updated.' }
        format.json { render :show, status: :ok, location: @execution }
      else
        format.html { render :edit }
        format.json { render json: @execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /executions/1
  # DELETE /executions/1.json
  def destroy
    @execution.destroy
    respond_to do |format|
      format.html { redirect_to executions_url, notice: 'Execution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_execution
      @execution = Execution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def execution_params
      params.require(:execution).permit(:executed_at, :executor_id)
    end
end

app/helpers/executions_helper.rb
module ExecutionsHelper
end

app/views/executions/_form.html.haml
= form_for @execution, html: { class: "form form-horizontal execution" } do |f|
  .form-group
    = f.label :executed_at, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :executed_at, class: 'form-control', required: true
    = f.error_span(:executed_at)
  .form-group
    = f.label :executor_id, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :executor_id, class: 'form-control', required: true
    = f.error_span(:executor_id)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), executions_path, :class => 'btn btn-default'

app/views/executions/edit.html.haml
- model_class = Execution
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/executions/index.html.haml
- model_class = Execution
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:executed_at)
      %th= model_class.human_attribute_name(:executor_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @executions.each do |execution|
      %tr
        %td= link_to execution.id, execution_path(execution)
        %td= execution.executed_at
        %td= execution.executor_id
        %td=l execution.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_execution_path(execution), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), execution_path(execution), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_execution_path, :class => 'btn btn-primary'

app/views/executions/new.html.haml
- model_class = Execution
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/executions/show.html.haml
- model_class = Execution
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:executed_at) + ':'
  %br
  = @execution.executed_at
%p
  %strong= model_class.human_attribute_name(:executor_id) + ':'
  %br
  = @execution.executor_id


= link_to t('.back', :default => t("helpers.links.back")), executions_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_execution_path(@execution), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), execution_path(@execution), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'