config/routes.rb
Rails.application.routes.draw do
  resources :test_results
  resources :test_result_types
  resources :executions
  resources :executors

  resources :projects do 
		resources :sections do 
  		resources :test_cases, shallow: true
		end
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :project
	has_many :test_cases
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:name, :project_id)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.haml
= form_for @section, html: { class: "form form-horizontal section" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control', required: true
    = f.error_span(:name)
  .form-group
    = f.label :project_id, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :project_id, class: 'form-control', required: true
    = f.error_span(:project_id)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), sections_path, :class => 'btn btn-default'

app/views/sections/edit.html.haml
- model_class = Section
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/sections/index.html.haml
- model_class = Section
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:project_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @sections.each do |section|
      %tr
        %td= link_to section.id, section_path(section)
        %td= section.name
        %td= section.project_id
        %td=l section.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_section_path(section), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), section_path(section), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_section_path, :class => 'btn btn-primary'

app/views/sections/new.html.haml
- model_class = Section
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/sections/show.html.haml
- model_class = Section
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @section.name
%p
  %strong= model_class.human_attribute_name(:project_id) + ':'
  %br
  = @section.project_id


= link_to t('.back', :default => t("helpers.links.back")), sections_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_section_path(@section), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), section_path(@section), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'